[package]
name = "spmc_ring"
version = "0.1.0"
authors = ["Todd Stellanova <tstellanova@users.noreply.github.com>"]
edition = "2018"


[dependencies]
generic-array = "0.14.2"
nb = {version="0.1.2"}


